### PR TITLE
fix: Prevent starting up if window is not defined

### LINKED ISSUE #246: Out-of-box SSR support
👋 folks! Alfa tester here 🧑‍🔬 Curious to hear your thoughts on this one!

### Environment

`"@sentry/replay": "0.6.4-0"`
`"next": "12.3.1"`

### Steps to Reproduce

1. Configure Sentry in a Next.js app [using a wizard](https://docs.sentry.io/platforms/javascript/guides/nextjs/)

2. Reuse one `sentryConfig` in `sentry.client.ts` and `sentry.server.ts` for simplicity (e.g. by importing `sentryConfig` from `sentry.client.ts` to `sentry.server.ts`)

3. Add `new Replay()` to a shared config

4. Try `next dev` or `next build`

### Expected Result

It just works™, i.e. `new Replay()` is a noop on the server

### Actual Result

💥

```
ReferenceError: window is not defined
    at isInternal (/path/to/project/node_modules/@sentry/replay/dist/index.js:158:56)
    at captureInternalException (/path/to/project/node_modules/@sentry/replay/dist/index.js:497:10)
    at new Replay (/path/to/project/node_modules/@sentry/replay/dist/index.js:1219:13)
    at eval (webpack-internal:///./sentry.client.config.ts:18:9)
    at Object../sentry.client.config.ts (/path/to/project/.next/server/pages/_app.js:142:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./sentry.server.config.ts:4:79)
    at Object../sentry.server.config.ts (/path/to/project/.next/server/pages/_app.js:1319:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/path/to/project/.next/server/pages/_app.js:2402:39)
[LATE_SETUP_CALL] {}
```

### Workaround

Do not reuse Sentry config, thus ensuring that `new Replay()` is only called in the client bundle. E.g.:

```ts
 integrations:
    typeof window === "undefined"
      ? []
      : [
          new Replay({
            // options
          }),
        ],
```

I’m fiddling with `sentry-replay` in https://github.com/blockprotocol/blockprotocol/pull/682 – any tips welcome!

### PR DESCRIPTION
**Pull request by ryan953**
Test notes:

I setup replays on my gatsby test app and was able to recreate the issue:

The config:
```typescript
#gatsby-config.ts

const config: GatsbyConfig = {
  ...
  plugins: [
    {
      resolve: "@sentry/gatsby",
    },
  ],
};
export default config;
```

```typescript
#sentry.config.ts

import * as Sentry from '@sentry/gatsby';
import { Replay } from "@sentry/replay";

Sentry.init({
  dsn: "https://c214503190724086b0b4017d8fe5d65a@o1176005.ingest.sentry.io/6622945",
  sampleRate: 1.0, // Adjust this value in production
  integrations: [
    new Replay(),
  ],
});
```

The failing output:
```bash
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: window is not defined


  1226 |         var _this = this;
  1227 |         // XXX: See method comments above
> 1228 |         window.setTimeout(function () { return _this.start(); });
       |         ^
  1229 |     };
  1230 |     /**
  1231 |      * Initializes the plugin.


  WebpackError: ReferenceError: window is not defined
```

After the fix we're able to build and run the app, and record replays:
| Test App | Replay |
| --- | --- |
| Screen Shot 2022-10-18 at 5 38 11 PM | Screen Shot 2022-10-18 at 5 37 09 PM |

In a gatsby app, or most of these other frameworks, it is possible to do have a node-only or browser-only config. With Gatsby, for example, I would remove `new Replay()` from `sentry.config.ts` and instead add `gatsby-browser.tsx` with this content to manually start the replay session (that's not better though, but it is a work around):
```typescript
const { Replay } = require("@sentry/replay");

exports.wrapRootElement = ({ element, props }) => {
  const replay = new Replay({
    blockAllMedia: false,
    maskAllText: false,
  });
  replay.start();

  return element;
};
```

Fixes #246

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -217,6 +219,9 @@ export class Replay implements Integration {
    * other global event processors to finish
    */
   setupOnce() {
+    if (!isBrowser) {
```
Comment (ryan953) [inline src/index.ts:222]: i only added the guard to these couple of methods because they're a) documented in the readme and b) entrypoints

I was looking at using the typescript `private` keyword, and prefixing all the other methods with underscore to prevent folks from calling them, but it seems like overkill so early on. Also, without the `_initialized` and `isEnabled` flags set, the plugin won't really work. The guards i have prevent those from being enabled.
